### ISSUE TITLE
Make the add-on available through NuGet

### ISSUE THREAD

**Issue by mk56-spn** [Guillemsc/GTweensGodot#2] opened 2023-10-03 12:55 UTC
First of all this looks amazing congratulations on your work so far! 

Sorry if feature requests aren't welcome, the discussion tab isn't enabled so I figured opening an issue was my best bet. 

The way godot does add-ons tends to pollute the user's folders especially when using any form of VCS . As such I think people would be grateful if offered a nuget package. I wouldn't mind attempting to make it myself if you have no interest.

**Comment by Guillemsc** [comment] 2023-10-03 13:40
Hello! Thank you so much! 

Feature requests are super welcome (I forgot to enable the discussion tab).

My initial idea was to have [example scenes](https://github.com/Guillemsc/GTweensGodot/tree/main/Godot/Examples), which are bundled with the library itself. AFAIK this would be incompatible with NuGet, since it only can bundle code.

*But*, I think that having it as a NuGet package would bring many benefits, so my next steps will be to separate the examples into a different repo. This way installation is easier, and I can create a NuGet package more easily.

**Comment by Guillemsc** [comment] 2023-10-03 14:08
I managed to create [a nuget package](https://www.nuget.org/packages/GTweensGodot/0.2.0) without any issue. The problem is that I relied on the Autoload Godot functionality for automatically create the node that updates all tweens. The issue is that I can't reference scripts from a NuGet package for Autoload.

**Comment by mk56-spn** [comment] 2023-10-03 14:26
Thats a good point, hmm not sure how this could be addressed. perhaps a stop gap solution would be adding some documentation that tells users to call a method that adds that autoload from their main scene, not ideal but it sounds workable no?

**Comment by mk56-spn** [comment] 2023-10-03 16:02
> I've added [this installation section](https://github.com/Guillemsc/GTweensGodot#from-nuget) for now, which explains the workaround to make it work. I'll see how it can be improved it in the future. Let me know if it works for you :)

will test in a bit! how would you wish to be credited in the project i'm planning to use it in?  aside from the MIT copy paste ofc. for stuff like credits ...

**Comment by Guillemsc** [comment] 2023-10-03 16:04
There is no need for credit! But if you still feel like, Guillem SC is fine :)

**Comment by mk56-spn** [comment] 2023-10-03 19:36
Works as expected! far better than the native tween system on most fronts.

**Comment by Guillemsc** [comment] 2023-10-03 19:48
Cool cool, closing this then 👍

**Closed by Guillemsc** 2023-10-03 19:48 UTC
Labels: feature request
